### ISSUE TITLE
bpi-r4 6.10 archive doesn't contain the kernel image

### ISSUE THREAD

**Issue by danielschonfeld** [frank-w/BPI-R2-4.14#127] opened 2024-08-30 01:02 UTC
no kernel image or anything at all in RPI-BOOT

**Comment by frank-w** [comment] 2024-08-30 05:07
You mean tar or deb package?

**Comment by danielschonfeld** [comment] 2024-08-30 11:37
The tar on the releases page of this repo

but speaking of where does one find Deb packages?

**Comment by frank-w** [comment] 2024-08-30 11:44
Seems this is caused by build error because i added older v0 dts for r4.
https://github.com/frank-w/BPI-Router-Linux/actions/runs/10620038816/job/29438942919#step:16:90
Will remove the release and fix this as soon as possible,thx for reporting

**Comment by danielschonfeld** [comment] 2024-08-30 11:47
Thank you and thanks for making all of this!

**Comment by frank-w** [comment] 2024-08-30 16:28
Fixed in latest release

https://github.com/frank-w/BPI-Router-Linux/releases/tag/CI-BUILD-6.10-main-6.10.0-2024-08-30_1239

**Closed as completed by frank-w** 2024-08-30 16:28 UTC
